product:
  abbott-dufaston-gyno
  abbott-femoston
  abbott-klacid-pediatric
  abbott-klacid-therapeutic
  abbott-omacore
  abbott-vaginorm
  abbott_ganaton
  abbott_heptral
  abbott_klacid_gastro
  abbott_klacid_iv
  abbott_klacid_ontime
  abbott_ontime
  abbott_scenario_builder
  betaserk
  blink
  dicetel
  duphalac
  duphaston
  duspatalin
  fevarin
  imudon
  imunorix
  influvac
  irs-19
  kreon
  physiotens
  rupafyn
  teveten
  traykor
specialty:
  cdAlpha1Cardiologists
  cdAlpha1Pharmacies
  cdAlpha1Therapeutists
  cdAlpha2Endocrinologists
  cdAlpha2Ophtalmologists
  cdAlpha2Pharmacies
  cdAlpha2Therapeutists
  cdAlphaUCardiologists
  cdAlphaUEndocrinologists
  cdAlphaUOphtalmologists
  cdAlphaUPharmacies
  cdAlphaUTherapeutists
  cdBetaENT
  cdBetaNarcology
  cdBetaNeurologists
  cdBetaPharmacies
  cdBetaPsychiatrists
  cdBetaTherapeutists
  gePharmacyOTC
  imAllergistCommon
  imAllergistGP
  imAllergistPed
  imClients
  imENTAdultsCommon
  imENTAdultsGP
  imENTChildrenCommon
  imENTChildrenPed
  imPediatristCommon
  imPediatristPed
  imPharmCircle
  imPharmacyCommon
  imPharmacyGP
  imPharmacyOTC
  imPharmacyPed
  imPulmonologistsCommon
  imPulmonologistsGP
  imTherapeuticCommon
  imTherapeuticGP
  otcOculists
  whTargetingVisit